fix on-tags.yml
since the workflow triggers on a tag, we end-up in detached head, where we can not push to.
As final releases should be pushed to master, we now create branch for each release, and merge them into master

https://github.com/orange-cloudfoundry/k3s-wrapper-boshrelease/actions/runs/7463021723/job/20306723910

pushing changes to git repository
[detached HEAD 93bf2a4] cutting release 0.4.0
 3 files changed, 35 insertions(+)
 create mode 100644 releases/k3s-wrapper/k3s-wrapper-0.4.0.yml
To https://github.com/orange-cloudfoundry/k3s-wrapper-boshrelease.git
 ! [rejected]        HEAD -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/orange-cloudfoundry/k3s-wrapper-boshrelease.git'